name: Handle issue
on: 
    issues:
        types: [opened, edited]
jobs:
    issue:
        runs-on: ubuntu-latest
        steps:
            - name: output event details
              run:  echo "${{toJson(github.event)}}"